# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyPermitSysApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MyPermitSysApplication.Request', verbose_name='Заявка'),
        ),
    ]
