# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 16:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyPermitSysApplication', '0002_permit_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionindepartment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='positionindepartment',
            name='position',
        ),
        migrations.RemoveField(
            model_name='request',
            name='position_in_department',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='request',
        ),
        migrations.AlterField(
            model_name='person',
            name='patronymic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='position_in_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RequestSysApplication.PositionInDepartment', verbose_name='Должность'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='PositionInDepartment',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
