# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPermitSysApplication', '0006_auto_20160424_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='passport_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='passport_serial',
            field=models.IntegerField(blank=True),
        ),
    ]
